In [ ]:
%config Completer.use_jedi = False

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: Config option `use_jedi` not recognized by `IPCompleter`.
  """Entry point for launching an IPython kernel.


In [42]:
import numpy as np

In [ ]:
a=np.arange(12,24,2)
print(a)

[12 14 16 18 20 22]


arange = arange([start,] stop[, step,], dtype=None)

In [ ]:
np.argsort(a, axis=-1, kind= None, order=None)

array([0, 1, 2, 3, 4, 5])

kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}

In [ ]:
np.argsort(a, axis=-1, kind= 'mergesort', order=None)

array([0, 1, 2, 3, 4, 5])

The numpy.all() function tests whether all array elements along the mentioned axis evaluate to True.
numpy.all() returns True only if all elements in a NumPy array evaluate to True.

In [ ]:
c = [[True, False], [True, True]]
arr = np.all(c)
arr

False

In [ ]:
c = [[True, True], [True, True]]
arr = np.all(c)
arr

True

np.any(a) to return True if at least one element in array a evaluates to True and False otherwise.

In [ ]:
c = [[True, False], [True, True]]
arr = np.any(c)
print(arr)

True


In [ ]:
c = [[False, False], [False, False]]
arr = np.any(c)
print(c)

[[False, False], [False, False]]


np.apply_along_axis(func1d, axis, arr, *args, **kwargs).

Addition of  first and last element of particular column of the array

In [ ]:
def func(a):
  return (a[0]+ a[-1])  # 
b = np.array([[2,4,6],     # 2+9
              [1,3,5],     # 4+7
              [9,7,8]])    # 6+8
np.apply_along_axis(func,0,b)


array([11, 11, 14])

Addition of  first and last element of particular row of the array

In [ ]:
def func(a):
  return (a[0]+ a[-1])  # 
b = np.array([[2,4,6],   #2+6
              [1,3,5],   #1+5
              [9,7,8]])  #9+8
np.apply_along_axis(func,1,b)


array([ 8,  6, 17])

np.argmax(a, axis=None, out=None)  

Return indices of the maximum values along the given axis.

In [ ]:
a = np.arange(6).reshape(2,3) + 10
a

array([[10, 11, 12],
       [13, 14, 15]])

In [ ]:
np.argmax(a)

5

In [ ]:
np.argmax(a, axis=0)

array([1, 1, 1])

In [ ]:
np.argmax(a, axis=1)

array([2, 2])

np.argmin(a, axis=None, out=None)

Returns the indices of the minimum values along an axis.



In [ ]:
np.argmin(a)

0

In [ ]:
np.argmin(a, axis=0)

array([0, 0, 0])

In [ ]:
np.argmin(a, axis=1)

array([0, 0])

np.argsort(a, axis=-1, kind=None, order=None)

Returns the indices that would sort an array.

In [ ]:
x = np.array([2, 1, 3])
np.argsort(x)

array([1, 0, 2])

In [ ]:
x = np.array([[0, 3], [2, 2]])
x

array([[0, 3],
       [2, 2]])

In [ ]:
ind = np.argsort(x, axis=0)
ind

array([[0, 1],
       [1, 0]])

In [ ]:
ind = np.argsort(x, axis=1)
ind

array([[0, 1],
       [0, 1]])

bincount(x, weights=None, minlength=0)

Count number of occurrences of each value in array of non-negative ints.

sizeof(bin) = max(array) +1

In [ ]:
y = np.bincount([4,6,7,4,2,4])
y

array([0, 0, 1, 0, 3, 0, 1, 1])

numpy.ceil(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj]) = <ufunc 'ceil'>¶

Return the ceiling of the input, element-wise.

The ceil of the scalar x is the smallest integer i, such that i >= x.

In [ ]:
a = np.array([-1.4, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])
np.ceil(a)

array([-1., -1., -0.,  1.,  2.,  2.,  2.])

np.clip(a, a_min, a_max, out=None, **kwargs)

Clip (limit) the values in an array.

In [ ]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.clip(a, 1, 8)

array([1, 1, 2, 3, 4, 5, 6, 7, 8, 8])

In [ ]:
np.clip(a, [3, 4, 1, 1, 1, 4, 4, 4, 4, 4], 8)

array([3, 4, 2, 3, 4, 5, 6, 7, 8, 8])

conjugate(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])


Return the complex conjugate, element-wise.

The complex conjugate of a complex number is obtained by changing the sign of its imaginary part.

In [38]:
np.conj is np.conjugate

True

In [39]:
np.conjugate(1+2j)

(1-2j)

In [40]:
x = np.eye(2) + 1j * np.eye(2)
np.conjugate(x)

array([[1.-1.j, 0.-0.j],
       [0.-0.j, 1.-1.j]])

**np.corrcoef**(x, y=None, rowvar=True, bias=<no value>, ddof=<no value>, *, dtype=None)


Return Pearson product-moment correlation coefficients.

Please refer to the documentation for cov for more detail. The relationship between the correlation coefficient matrix, R, and the covariance matrix, C, is

R_{ij} = \frac{ C_{ij} } { \sqrt{ C_{ii} * C_{jj} } }

The values of R are between -1 and 1, inclusive.



Consider two variables, x_0 and x_1, which correlate perfectly, but in opposite directions:

In [44]:
x = np.array([[0, 2], [1, 1], [2, 0]]).T
x

array([[0, 1, 2],
       [2, 1, 0]])

Note how x_0 increases while x_1 decreases. The covariance matrix shows this clearly:

In [45]:
np.cov(x)

array([[ 1., -1.],
       [-1.,  1.]])

np.cross(a, b, axisa=-1, axisb=-1, axisc=-1, axis=None)

Return the cross product of two (arrays of) vectors.

In [46]:
x = [1, 2, 3]
y = [4, 5, 6]
np.cross(x, y)

array([-3,  6, -3])

The orientation of c can be changed using the axisc keyword.

In [47]:
np.cross(x, y, axisc=0)

array([-3,  6, -3])

np.cumprod(a, axis=None, dtype=None, out=None)

Return the cumulative product of elements along a given axis.

In [49]:
a = np.array([1,2,3])
np.cumprod(a)

array([1, 2, 6])

In [58]:
d = np.array([[1, 2, 3], [4, 5, 6]])

In [59]:
np.cumprod(d, axis=0)

array([[ 1,  2,  3],
       [ 4, 10, 18]])

In [60]:
np.cumprod(d,axis=1)

array([[  1,   2,   6],
       [  4,  20, 120]])

np.cumsum(a, axis=None, dtype=None, out=None)

Return the cumulative sum of the elements along a given axis.



In [62]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
np.cumsum(a)

array([ 1,  3,  6, 10, 15, 21])

np.diff(a, n=1, axis=-1, prepend=numpy._globals._NoValueType instance, append=numpy._globals._NoValueType instance)

Calculate the n-th discrete difference along the given axis.

The first difference is given by out[i] = a[i+1] - a[i] along the given axis, higher differences are calculated by using diff recursively.

In [67]:
x = np.array([1, 2, 4, 7, 0])
np.diff(x)

array([ 1,  2,  3, -7])

In [68]:
np.diff(x, n=2)

array([  1,   1, -10])

numpy.dot(a, b, out=None)

Gives Dot product of two arrays

In [69]:
np.dot(3, 4)

12

In [70]:
np.dot([2j, 3j], [2j, 3j])

(-13+0j)

In [71]:
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]
np.dot(a, b)

array([[4, 1],
       [2, 2]])

numpy.floor(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj]) = <ufunc 'floor'>

Return the floor of the input, element-wise.

The floor of the scalar x is the largest integer i, such that i <= x. It is often denoted as \lfloor x \rfloor.

In [72]:
a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])
np.floor(a)

array([-2., -2., -1.,  0.,  1.,  1.,  2.])

numpy.inner(a, b)

Inner product of two arrays.

np.inner(a, b) = sum(a[:]*b[:])

In [73]:
a = np.array([1,2,3])
b = np.array([0,1,0])
np.inner(a, b)

2

In [82]:
a = np.arange(12).reshape((6,2))
b = np.arange(4)
a

SyntaxError: ignored

In [77]:
b

array([0, 1, 2, 3])

In [78]:
np.inner(a, b)

array([[ 14,  38,  62],
       [ 86, 110, 134]])