Basic of numpy

In [ ]:
import numpy as np
a = np.arange(6)#specify range of number
print(a)

[0 1 2 3 4 5]


In [ ]:
a.shape #gives the shape of array

(6,)

In [ ]:
a2 = a[np.newaxis, :]# np.newaxis to add a new axis:
print(a2)


[[0 1 2 3 4 5]]


In [ ]:
print(a2.shape)#define shape of array

(1, 6)


In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])#simply print number present in arary
print(a)

[1 2 3 4 5 6]


In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])#convert into matrix
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
a=[1, 2 , 3, 4]#define index value
print(a[0])


1


This section covers 1D array, 2D array, ndarray, vector, matrix

In [ ]:
 #two dimensional
 [[0., 0., 0.],
 [1., 1., 1.]] #n NumPy, dimensions are called axes. This means that if you have a 2D array that looks like this

In [ ]:
import numpy as np
 a = np.array([1, 2, 3]) #To create a NumPy array, you can use the function np.array().

In [ ]:
a=np.zeros(2)#print 0
print(a)

[0. 0.]


In [ ]:
a=np.ones(2)
print(a)

[1. 1.]


In [ ]:
a=np.empty(6) # crete an empty ndarray with  some random data
print(a)


[4.9e-324 9.9e-324 1.5e-323 2.0e-323 2.5e-323 3.0e-323]


In [ ]:
np.arange(2, 9, 2) # specify the number within 9 and with difference of 2

array([2, 4, 6, 8])

In [ ]:
np.empty(2)#daut

array([1., 1.])

In [ ]:
np.linspace(0, 10, num=5) #create an array with values that are spaced linearly in a specified interval:

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
x = np.ones(2, dtype=np.int64) #you can explicitly specify which data type you want using the dtype keyword.
print(x)

[1 1]


Adding, removing, and sorting elements

In [ ]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [ ]:
np.sort(arr) #sort the numbers in ascending order 

array([1, 2, 3, 4, 5, 6, 7, 8])


#argsort - works with real/complex arrays containing nan values

In [ ]:
#one dimension
import numpy as np
x = np.array([3, 1, 2]) #numpy.argsort(a, axis=-1, kind=None, order=None)
np.argsort(x)


array([1, 2, 0])

In [ ]:
#twodimension

x = np.array([[0, 3], [2, 2]])
x

array([[0, 3],
       [2, 2]])

In [ ]:
ind = np.argsort(x, axis=0)  # sorts along first axis (down)
ind

array([[0, 1],
       [1, 0]])

In [ ]:
np.take_along_axis(x, ind, axis=0)  # same as np.sort(x, axis=0)#daut

array([[0, 2],
       [2, 3]])

In [ ]:
ind = np.argsort(x, axis=1)  # sorts along last axis (across)
ind

array([[0, 1],
       [0, 1]])

In [ ]:
np.take_along_axis(x, ind, axis=1)  # same as np.sort(x, axis=1)

array([[0, 3],
       [2, 2]])

In [ ]:
ind = np.unravel_index(np.argsort(x, axis=None), x.shape)#daut
ind

(array([0, 1, 1, 0]), array([0, 0, 1, 1]))

In [ ]:
x[ind]  # same as np.sort(x, axis=None)


array([0, 2, 2, 3])

In [ ]:
#Sorting with keys:

x = np.array([(1, 0), (0, 1)], dtype=[('x', '<i4'), ('y', '<i4')])
x

array([(1, 0), (0, 1)], dtype=[('x', '<i4'), ('y', '<i4')])

In [ ]:
np.argsort(x, order=('x','y'))

array([1, 0])

#lexsort

In [ ]:
surnames =    ('Hertz',    'Galilei', 'Hertz')#daut
first_names = ('Heinrich', 'Galileo', 'Gustav')
ind = np.lexsort((first_names, surnames))
ind


array([1, 2, 0])

In [ ]:
[surnames[i] + ", " + first_names[i] for i in ind]#daut

['Galilei, Galileo', 'Hertz, Gustav', 'Hertz, Heinrich']

In [ ]:
#Sort two columns of numbers:


a = [1,5,1,4,3,4,4] # First column
b = [9,4,0,4,0,2,1] # Second column
ind = np.lexsort((b,a)) # Sort by a, then by b
ind

array([2, 0, 4, 6, 5, 3, 1])

In [ ]:
[(a[i],b[i]) for i in ind]#daut

[(1, 0), (1, 9), (3, 0), (4, 1), (4, 2), (4, 4), (5, 4)]

numpy.searchsorted

In [ ]:
import numpy as np#daut

np.searchsorted([1,2,3,4,5], 3)

2

In [ ]:
np.searchsorted([1,2,3,4,5], 3, side='right')#daut

2

In [ ]:
np.searchsorted([1,2,3,4,5], [-10, 10, 2, 3])#daut

array([0, 5, 1, 2])

#Numpy partition

In [ ]:
a = np.array([3, 4, 2, 1])#daut
np.partition(a, 3)

array([2, 1, 3, 4])

In [ ]:
np.partition(a, (1, 3))#daut

array([1, 2, 3, 4])

#numpy argpartition

In [ ]:
#one dimensional
x = np.array([3, 4, 2, 1])#daut
x[np.argpartition(x, 3)]

array([2, 1, 3, 4])

In [ ]:
#multi-dimentional
x = np.array([[3, 4, 2], [1, 3, 1]])#daut
index_array = np.argpartition(x, kth=1, axis=-1)
np.take_along_axis(x, index_array, axis=-1)  # same as np.partition(x, kth=1)

array([[2, 3, 4],
       [1, 1, 3]])

#numpy partition

In [ ]:
import numpy as np
a = np.array([3, 4, 2, 1])
np.partition(a, 3)

array([2, 1, 3, 4])

In [ ]:
import numpy as np 
np.partition(a, (1, 3))

array([1, 2, 3, 4])

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [ ]:
np.concatenate((a, b))#concatenate two array


array([1, 2, 3, 4, 5, 6, 7, 8])