In [ ]:
import numpy as np

NumPy as np: 
NumPy is usually imported under the np alias. alias: In Python alias are an alternate name for referring to the same thing.

In [ ]:
arr = np.arange(0,12,2)
print(arr)

[ 0  2  4  6  8 10]


 It creates an instance of ndarray with evenly spaced values and returns the reference to it.

You can define the interval of the values contained in an array, space between them, and their type with four parameters of arange():

**syntax:numpy.arange([start, ]stop, [step, ], dtype=None) -> numpy.ndarray**

In [ ]:
arr.shape

(6,)

NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

**Adding a new axis**


In [ ]:
arr[np.newaxis,:].shape

(1, 6)

np.newaxis is used to increase the dimension of the existing array by one more.

In [ ]:
arr.reshape(1,-1).shape

(1, 6)

-1 work same as '**:**' and 1 representing the one dimension adding in row

In [ ]:
arr[:,np.newaxis].shape

(6, 1)

It add one  dimension at the coloumn.

In [ ]:
arr.reshape(-1,1).shape

(6, 1)

**np.newaxis vs reshape**


**np.newaxis**:
It uses the slicing operator to recreate the array.
The dimension is temporarily added at the position of np.newaxis in the array. ‘None’ can also be used in place of np.newaxis.


**np.reshape:**
It is used to reshape the array to the desired layout.


In [ ]:
np.expand_dims(arr,axis=1).shape

(6, 1)

In [ ]:
np.expand_dims(arr,axis=0).shape

(1, 6)

This function expands the array by inserting a new axis at the specified position. Two parameters are required by this function.

**np.expand_dims(arr, axis)**

axis=1 means it add new axis at col position.

axis=0 means it add new axis at row position.

**np functions to create arrays¶**

In [33]:
np.zeros(2)

array([0., 0.])

Return a new array of given shape and type, filled with zeros.


In [ ]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones(shape=(4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

Return a new array of given shape and type, filled with ones.

In [34]:
np.empty(shape=(2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

Return a new array of given shape and type, without initializing entries.

This is faster than np.zeros

**Creating arrays**

In [35]:
np.linspace(1,100,20)

array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ])

The output array in this instance contains 20 equally spaced values between 1 and 100, which is just the numbers from 1 to 100.

In [36]:
np.random.rand(3,2,1)

array([[[0.27340974],
        [0.54235298]],

       [[0.58582038],
        [0.93775209]],

       [[0.84406744],
        [0.20603078]]])

The nprandom.rand() function creates an array of specified shape (3,2,1) and fills it with random values.


In [ ]:
np.random.randint(0,5,size=(3,2))

array([[2, 1],
       [4, 4],
       [3, 1]])

It returns an array of specified shape and fills it with random integers from low (inclusive) to high (exclusive), i.e. in the interval [low, high).

In [37]:
np.random.randn(3,2,2)

array([[[-2.82914162, -0.68842487],
        [ 2.69115826, -0.90192501]],

       [[-0.7345995 , -0.35318109],
        [-0.39395213,  2.38284555]],

       [[ 0.29623487,  0.271525  ],
        [ 0.13445072, -0.33222419]]])

The np.random.randn() function creates an array of specified shape (3,2,2) and fills it with random values as per standard normal distribution.

In [38]:
arr = np.random.randint(0,5,size=(5,))
arr

array([0, 0, 2, 2, 0])

In [39]:
np.sort(arr)

array([0, 0, 0, 2, 2])


Method to sort an array not in-place.

In [40]:
arr

array([0, 0, 2, 2, 0])

In [41]:
arr.sort()

In [42]:
arr

array([0, 0, 0, 2, 2])

Return a sorted copy of an array.

Method to sort an array in-place.

**argsort**

In [43]:
import numpy as np
arr= np.argsort([456,11,63])  
arr

array([1, 2, 0])

The NumPy module provides a function for performing an indirect sort along with the given axis with the help of the algorithm specified by the keyword. This function returns an array of indices of the same shape as 'arr', which would sort the array.

In [44]:
arr = np.array([[0, 5], [3, 2]])  #sort along first axis(down).
a = np.argsort(arr, axis=0)    
a   

array([[0, 1],
       [1, 0]])

In [26]:
np.take_along_axis(arr, a, axis=0)   # same as np.sort(x, axis=0)


array([[0, 2],
       [3, 5]])

In [28]:
np.argsort(arr, axis=1)  # sorts along last axis (across)

array([[0, 1],
       [1, 0]])

In [45]:
a = np.unravel_index(np.argsort(arr, axis=None), arr.shape) 
a


(array([0, 1, 1, 0]), array([0, 1, 0, 1]))

Indices of the sorted elements of a N-dimensional array.