**logspace** numpy :

np.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None, axis=0)

In [3]:
import numpy as np

Return numbers spaced evenly on a log scale.

In [6]:
np.logspace(12.0, 30.0, num=5)

array([1.00000000e+12, 3.16227766e+16, 1.00000000e+21, 3.16227766e+25,
       1.00000000e+30])

mgrid :  

In [26]:
np.mgrid[1:5,0:5] 


array([[[1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]])

1:5 => range 1 to 5 for the first array , it works on the basis of row . here , 5 indicates number of rows.

0:5 = > range of values from 0 to 5 , it works on the basis of column .Here 5 indicates number of columns.

In [27]:
np.mgrid[-1:1:5j]

array([-1. , -0.5,  0. ,  0.5,  1. ])

**ogrid**: 

In [36]:
np.ogrid[1:5,2:5]

[array([[1],
        [2],
        [3],
        [4]]), array([[2, 3, 4]])]

1:5 => values ranging from 1 to 5 ,1 dimensional arr in 5 rows 

2:5 => values ranging from 2 to 5 , 
number of values 5-2 = 3

numpy.**ones_like**(a, dtype=None, order='K', subok=True, shape=None)

Return an array of ones with the same shape and type as a given array.

In [37]:
x = np.arange(8)
x = x.reshape((2, 4))
x

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [38]:
np.ones_like(x)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

numpy.**zeros_like**(a, dtype=None, order='K', subok=True, shape=None)

Return an array of ones with the same shape and type as a given array.

In [39]:
x = np.arange(6)
x = x.reshape((2, 3))
x

array([[0, 1, 2],
       [3, 4, 5]])

In [40]:
np.ones_like(x)

array([[1, 1, 1],
       [1, 1, 1]])