repeat, squeeze, swapaxes, take, 
# nonzero, where, ptp,
# choose, compress, cumprod, cumsum, inner, ndarray.fill, imag, prod, put, putmask, real,


# *#repeat*- syn:numpy.repeat(arr, repetitions, axis = None)

In [ ]:
import numpy as np

np.repeat(3, 4)

array([3, 3, 3, 3])

In [ ]:
x = np.array([[1,2],[3,4]])
np.repeat(x, 2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [ ]:
np.repeat(x, 3, axis=1)

array([[1, 1, 1, 2, 2, 2],
       [3, 3, 3, 4, 4, 4]])

In [ ]:
np.repeat(x, [1, 2], axis=0)

array([[1, 2],
       [3, 4],
       [3, 4]])

## #Squeeze -syn:numpy.squeeze(a, axis=None)

In [ ]:
Remove axes of length one from a.

In [ ]:
import numpy as np
x = np.array([[[0], [1], [2]]])
x.shape

(1, 3, 1)

In [ ]:
np.squeeze(x).shape
(3,)

(3,)

In [ ]:
np.squeeze(x, axis=0).shape


(3, 1)

In [ ]:
np.squeeze(x, axis=1).shape

ValueError: ignored

In [ ]:
np.squeeze(x, axis=2).shape


(1, 3)

In [ ]:
x = np.array([[1234]])
x.shape

(1, 1)

In [ ]:
np.squeeze(x)

array(1234)

In [ ]:
np.squeeze(x).shape

()

In [ ]:
np.squeeze(x)[()]

1234

#ptp-The numpy. ptp() function returns the range (maximum-minimum) of values along an axis.

 preserves the data type of the array. This means the return value for an input of signed integers with n bits (e.g. np.int8, np.int16, etc)

In [ ]:
import numpy as np

x = np.array([[4, 9, 2, 10],
              [6, 9, 7, 12]])

In [ ]:
np.ptp(x, axis=1)#daut

array([8, 6])

In [ ]:
np.ptp(x, axis=0)#daut

array([2, 0, 5, 2])

In [ ]:
np.ptp(x)#daut

10

In [ ]:
import numpy as np  #d
y = np.array([[1, 127],
              [0, 127],
              [-1, 127],
              [-2, 127]], dtype=np.int8)

In [ ]:
np.ptp(y, axis=1)#This example shows that a negative value can be returned when the input is an array of signed integers.

array([ 126,  127, -128, -127], dtype=int8)

In [ ]:
np.ptp(y, axis=1).view(np.uint8)

array([126, 127, 128, 129], dtype=uint8)

#Choose
 syn:numpy.choose(a, choices, out=None, mode='raise')[source]
 
 With the help of Numpy numpy.choose() method, we can select the elements from an multidimensional array by passing a parameter as an array which contain the index of row number to be selected. Output array having the same size as passed in the parameter.

In [ ]:
import numpy as np


In [ ]:
np.random.choice(5, 3)#np.random.choice(5, 3)

array([3, 2, 3])

In [ ]:
a = [[1, 0, 1], [0, 1, 0], [1, 0, 1]]#d
choices = [-10, 10]
np.choose(a, choices)

array([[ 10, -10,  10],
       [-10,  10, -10],
       [ 10, -10,  10]])

In [ ]:
a = np.array([0, 1]).reshape((2,1,1))#d
c1 = np.array([1, 2, 3]).reshape((1,3,1))
c2 = np.array([-1, -2, -3, -4, -5]).reshape((1,1,5))
np.choose(a, (c1, c2)) # result is 2x3x5, res[0,:,:]=c1, res[1,:,:]=c2


array([[[ 1,  1,  1,  1,  1],
        [ 2,  2,  2,  2,  2],
        [ 3,  3,  3,  3,  3]],

       [[-1, -2, -3, -4, -5],
        [-1, -2, -3, -4, -5],
        [-1, -2, -3, -4, -5]]])

#numpy.compress(condition, a, axis=None, out=None)
Return selected slices of an array along given axis.

In [ ]:
a = np.array([[1, 2], [3, 4], [5, 6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
np.compress([0, 1], a, axis=0)

array([[3, 4]])

In [ ]:
np.compress([False, True, True], a, axis=0)

array([[3, 4],
       [5, 6]])

In [ ]:
np.compress([False, True], a, axis=1)

array([[2],
       [4],
       [6]])

#numpy cumpod
numpy.cumprod(a, axis=None, dtype=None, out=None)


In [12]:
a = np.array([1,2,3])
np.cumprod(a) 

array([1, 2, 6])

In [13]:
np.cumprod(a, axis=0)

array([1, 2, 6])

#numpy.cumsum
numpy.cumsum(a, axis=None, dtype=None, out=None)

In [17]:
import numpy as np
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
np.cumsum(a)

array([ 1,  3,  6, 10, 15, 21])

In [19]:
np.cumsum(a, dtype=float)     # specifies type of output value(s)

array([ 1.,  3.,  6., 10., 15., 21.])

In [20]:
np.cumsum(a,axis=0)

array([[1, 2, 3],
       [5, 7, 9]])

In [21]:
np.cumsum(a,axis=1)

array([[ 1,  3,  6],
       [ 4,  9, 15]])

#numpy.inner
numpy.inner(a, b)
Inner product of two arrays.

In [22]:
a = np.array([1,2,3])
b = np.array([0,1,0])

In [23]:
a = np.arange(24).reshape((2,3,4))#multidimensional array
b = np.arange(4)
np.inner(a, b)

array([[ 14,  38,  62],
       [ 86, 110, 134]])

In [24]:
np.inner(np.eye(2), 7)#An example where b is a scalar:

array([[7., 0.],
       [0., 7.]])

#numpy.ndarray.fill

ndarray.fill(value)
Fill the array with a scalar value.

In [28]:
import numpy as np


In [31]:
a = np.array([1, 2])
a.fill(0)
a

array([0, 0])

In [32]:
a = np.empty(2)
a.fill(1)
a

array([1., 1.])

#numpy.imag
syn:numpy.imag(val)

In [33]:
a = np.array([1+2j, 3+4j, 5+6j])
a.imag

array([2., 4., 6.])

In [34]:
a.imag = np.array([8, 10, 12])
a

array([1. +8.j, 3.+10.j, 5.+12.j])

Numpy.prod


In [38]:

np.prod([1.,2.])#By default, calculate the product of all elements:

2.0

In [39]:
np.prod([[1.,2.],[3.,4.]])#Even when the input array is two-dimensional:

24.0

In [40]:
np.prod([[1.,2.],[3.,4.]], axis=1)# specify the axis over which to multiply:

array([ 2., 12.])

In [41]:
np.prod([1., np.nan, 3.], where=[True, False, True])

3.0

In [42]:
x = np.array([1, 2, 3], dtype=np.uint8)
np.prod(x).dtype == np.uint

True

In [ ]:
np.prod([1, 2], initial=5

#numpy.put
syn:numpy.put(a, ind, v, mode='raise')
#Replaces specified elements of an array with given values.

In [43]:
a = np.arange(5)
np.put(a, [0, 2], [-44, -55])
a

array([-44,   1, -55,   3,   4])

In [44]:
a = np.arange(5)
np.put(a, 22, -5, mode='clip')
a

array([ 0,  1,  2,  3, -5])

#numpy.putmask
syn:numpy.putmask(a, mask, values)
#Changes elements of an array based on conditional and input values.

In [45]:
x = np.arange(6).reshape(2, 3)
np.putmask(x, x>2, x**2)
x

array([[ 0,  1,  2],
       [ 9, 16, 25]])

In [46]:
x = np.arange(5)#If values is smaller than a it is repeated:
np.putmask(x, x>1, [-33, -44])
x

array([  0,   1, -33, -44, -33])

#numpy.real
numpy.real(val)#
Return the real part of the complex argument.

In [47]:
a = np.array([1+2j, 3+4j, 5+6j])# gives original values
a.real

array([1., 3., 5.])

In [48]:
a.real = 9
a

array([9.+2.j, 9.+4.j, 9.+6.j])

In [49]:
a.real = np.array([9, 8, 7])#gives complexvalues
a

array([9.+2.j, 8.+4.j, 7.+6.j])

In [50]:
np.real(1 + 1j)


1.0