In [ ]:
# fromfile, # Remaining numppy functions for exploration
# fromfile, fromfunction, identity, linspace, logspace, mgrid, ogrid, ones_like, zeros_like

In [5]:
import numpy as np

**fromfile**

In [ ]:
Construct an array from data in a text or binary file.

A highly efficient way of reading binary data with a known data-type, as well as parsing simply formatted text files.
 Data written using the tofile method can be read using this function.
 numpy.fromfile(file, dtype=float, count=-1, sep='', offset=0, *, like=None)¶

In [7]:
dt = np.dtype([('time', [('min', np.int64), ('sec', np.int64)]),
               ('temp', float)])  #Construct an ndarray:
x = np.zeros((1,), dtype=dt)
x['time']['min'] = 10; x['temp'] = 98.25
x 

array([((10, 0), 98.25)],
      dtype=[('time', [('min', '<i8'), ('sec', '<i8')]), ('temp', '<f8')])

In [13]:
dt = np.dtype([('time', [('min',np.int64), ('sec',np.int64)]),
                    ('temp',float)])
x=np.zeros((1,), dtype=dt)
x['time']['min']=20; x['temp']=23.75
x

            

array([((20, 0), 23.75)],
      dtype=[('time', [('min', '<i8'), ('sec', '<i8')]), ('temp', '<f8')])

In [14]:
import tempfile
fname = tempfile.mkstemp()[1]   #Save the raw data to disk:
x.tofile(fname)

In [15]:
np.fromfile(fname, dtype=dt)  #Read the raw data from disk:


array([((20, 0), 23.75)],
      dtype=[('time', [('min', '<i8'), ('sec', '<i8')]), ('temp', '<f8')])

In [16]:
np.save(fname, x)        #The recommended way to store and load data:
np.load(fname + '.npy')

array([((20, 0), 23.75)],
      dtype=[('time', [('min', '<i8'), ('sec', '<i8')]), ('temp', '<f8')])

**numpy.fromfunction**

In [ ]:
Construct an array by executing a function over each coordinate.

The resulting array therefore has a value fn(x, y, z) at coordinate (x, y, z).


In [17]:
np.fromfunction(lambda i, j: i == j, (3, 3), dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [18]:
np.fromfunction(lambda i, j: i + j, (3, 3), dtype=int)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [19]:
np.fromfunction(lambda i, j: i - j, (3, 3), dtype=int)

array([[ 0, -1, -2],
       [ 1,  0, -1],
       [ 2,  1,  0]])

**identity**

 Return a identity matrix i.e. a square matrix with ones on the main diagonal.
 

In [20]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])