In [3]:
import numpy as np

this is use to import numpy library into your Python script

In [2]:
x = np.arange(0,20,5) # similar to range
print(x)

[ 0  5 10 15]


In [3]:
np.arange(-5,5)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

arange([start,] stop[, step,][, dtype]) : Returns an array with evenly spaced elements as per the interval. 

In [4]:
ar = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(ar.shape)

(2, 4)


NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.


***Adding a new axis***

In [5]:
ar[np.newaxis,:].shape

(1, 2, 4)

Numpy Newaxis is an object that is included in the array to expand the dimension of the given array. 

In [6]:
x.reshape(1,-1).shape

(1, 4)


-1 work same as ':' and 1 representing the one dimension adding in row

In [7]:
x[:,np.newaxis].shape

(4, 1)

this method use to add one dimension at the coloumn.

In [8]:
x.reshape(-1,1).shape

(4, 1)

np.reshape: It is used to reshape the array to the desired layout.

In [9]:
np.expand_dims(x,axis=1).shape

(4, 1)

In [10]:
np.expand_dims(x,axis=0).shape

(1, 4)

Python Numpy expand_dims() method expands the array by inserting a new axis at the specified position.


***np functions to create arrays***

In [11]:
np.zeros(4)

array([0., 0., 0., 0.])

The Numpy zeros() method in Python creates a new array of the specified shape and type, with all of its elements initialized to 0.

In [12]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones(shape=(4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

This is very similar to Numpy Zero. Here Numpy zeros function returns a numpy array of only ones with specified shape and data type

In [14]:
np.empty(shape=(2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

The empty() method of Python numpy class returns a new array of the specified shape and type, without initializing the entries.

***Creating arrays***

In [15]:
np.linspace(1,100,20)

array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ])

The numpy.linspace() function returns number spaces evenly w.r.t interval. Similar to numpy.arange() function but instead of step it uses sample number.

In [16]:
np.random.rand(3,2,1)

array([[[0.30118215],
        [0.98658746]],

       [[0.99305518],
        [0.60967247]],

       [[0.99557202],
        [0.62575068]]])

The rand() function work like random() but it accept shape and return ndarray which contain random values between 0.0 to 1.0.

In [18]:
np.random.randint(0,5,size=(3,3))

array([[4, 3, 0],
       [3, 0, 4],
       [4, 1, 0]])

The random integer function generates single random integer number from given range and if the shape will give then return ndarray.

In [20]:
np.random.randn(3,3,2)

array([[[-0.5978703 , -0.92864689],
        [-0.84722885, -0.73693495],
        [-0.88872079,  0.85617008]],

       [[-1.16928277, -0.55011328],
        [-1.57313898, -1.24585026],
        [-0.94605051,  0.10543662]],

       [[-0.19178065, -0.31803811],
        [ 1.45875692,  1.55817857],
        [-2.02584252,  1.49678171]]])

The randn() function work like rand() function but it reurn samples of  standerd normalise distribution value.

In [25]:
arr = np.random.randint(0,5,size=(5,))
arr

array([2, 0, 2, 0, 2])

numpy.random.randint() is one of the function for doing random sampling in numpy. It returns an array of specified shape and fills it with random integers from low (inclusive) to high (exclusive), i.e. in the interval [low, high).

In [26]:
np.sort(x)

array([2, 3, 3, 4, 4])

Syntax :numpy.sort(a, axis=-1, kind=None, order=None)

 Return a sorted copy of an array.



In [27]:
x

array([2, 4, 3, 4, 3])

In [29]:
x.sort()

In [30]:
x

array([2, 3, 3, 4, 4])

In [31]:
y = np.array([3, 1, 2])
np.argsort(y)

array([1, 2, 0])

numpy.argsort(a, axis=-1, kind=None, order=None)

Returns the indices that would sort an array.

Perform an indirect sort along the given axis using the algorithm specified by the kind keyword. It returns an array of indices of the same shape as a that index data along the given axis in sorted order.



In [35]:
surnames =    ('Hertz',    'Galilei', 'Hertz')
first_names = ('Heinrich', 'Galileo', 'Gustav')
ind = np.lexsort((first_names, surnames))
ind
[surnames[i] + ", " + first_names[i] for i in ind]

['Galilei, Galileo', 'Hertz, Gustav', 'Hertz, Heinrich']

function performs an indirect sort using a sequence of keys. The keys can be seen as a column in a spreadsheet. The function returns an array of indices, using which the sorted data can be obtained.

In [37]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 9)

print(x)

3


There is a method called searchsorted() which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.

In [40]:
a = np.array([3, 3, 2, 10, 6, 8, 4, 2, 1])
np.partition(a, 3)

array([ 2,  1,  2,  3,  3,  8,  4, 10,  6])

**partitions** : Creates a copy of the array with its elements rearranged in such a way that the value of the element in k-th position is in the position it would be in a sorted array. All elements smaller than the k-th element are moved before this element and all equal or greater are moved behind it. The ordering of the elements in the two partitions is undefined.

In [41]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

numpy.concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")
Join a sequence of arrays along an existing axis.

In [43]:
x = np.array([[1, 2, 3], [3, 4, 5]])
x.ndim

2

ndarray.ndim is use to find the Number of array dimensions.

In [3]:
x = np.zeros((3, 5, 2), dtype=np.complex128)
x.size

30

numpy.ndarray.size() function return the number of elements in the array. it equal to np.prod(a.shape), i.e., the product of the array’s dimensions.

In [4]:
x = np.array([1, 2, 3, 4])
x.shape

(4,)

The shape property is usually used to get the current shape of an array, but may also be used to reshape the array in-place by assigning a tuple of array dimensions to it.

In [6]:
a = np.random.randint(0,10,size=(3,3))
a

array([[9, 0, 2],
       [0, 1, 2],
       [6, 7, 3]])

In [7]:
a[a>4]

array([9, 6, 7])

In [8]:
a>5

array([[ True, False, False],
       [False, False, False],
       [ True,  True, False]])

In [9]:
a[(a>4) & (a%2==0)]

array([6])

In [10]:
a[(a<4) | (a%2==0)]

array([0, 2, 0, 1, 2, 6, 3])

In [11]:
a = np.arange(1,13)
a = a.reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
b = np.nonzero(a<5)
b

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))

In [14]:
list(zip(b[0],b[1])) #list of co-ordinates

[(0, 0), (0, 1), (0, 2), (0, 3)]

In [15]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In order to ‘slice’ in numpy, you will use the colon (:) operator and specify the starting and ending value of the index.

In [16]:
arr = np.array([1, 2, 3, 4])

print(arr[0])

1


You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [18]:
a = np.array([[1], [2], [3]])
b = np.array([[2], [3], [4]])
np.vstack((a,b))

array([[1],
       [2],
       [3],
       [2],
       [3],
       [4]])

numpy.vstack(tup)
Stack arrays in sequence vertically (row wise).

In [20]:
a = np.array((1,2,3))
b = np.array((2,3,4))
np.hstack((a,b))

array([1, 2, 3, 2, 3, 4])

numpy.hstack(tup)
Stack arrays in sequence horizontally (column wise).

In [21]:
x = np.arange(16.0).reshape(4, 4)
x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

numpy.hsplit(ary, indices_or_sections)
Split an array into multiple sub-arrays horizontally (column-wise)

In [22]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


 the view is just a view of the original array.The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [23]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

In [24]:
arr = np.array([[2, 2], [2, 2]])
arr

array([[2, 2],
       [2, 2]])

In [25]:
arr.sum()

8

In [26]:
arr.sum(axis=0)

array([4, 4])

In [27]:
arr.sum(axis=1)

array([4, 4])

In [29]:
np.unique([1, 1, 2, 2, 3, 3])

array([1, 2, 3])

numpy.unique(ar, return_index=False, return_inverse=False, return_counts=False, axis=None)
Find the unique elements of an array.

In [30]:
a = np.array(['a', 'b', 'b', 'c', 'a'])
u, indices = np.unique(a, return_index=True)
u

array(['a', 'b', 'c'], dtype='<U1')

In [31]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])
np.unique(a_2d, axis=0)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Find the unique elements of an array

In [32]:
a_2d = np.array([[1, 2, 3, 1], [5, 6, 7, 5], [9, 10, 11, 9], [1, 2, 3, 1]])
a_2d = np.unique(a_2d, axis=0) 
a_2d

array([[ 1,  2,  3,  1],
       [ 5,  6,  7,  5],
       [ 9, 10, 11,  9]])

Removes duplicate rows

In [33]:
a_2d = np.unique(a_2d, axis=1)
a_2d

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

Removes duplicate columns

In [34]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])
unique_rows, indices, occurrence_count = np.unique(a_2d, axis=0, return_counts=True, return_index=True)
print(unique_rows)

print(indices)
print(occurrence_count)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[0 1 2]
[2 1 1]


 its returns indices and count of unique rows

In [36]:
A = np.arange(8).reshape((2,2,2))
A

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [37]:
np.flip(A, 0)

array([[[4, 5],
        [6, 7]],

       [[0, 1],
        [2, 3]]])

it is use to reverse an array

In [38]:
 y = np.array([[2,3], [4,5]])
 y.flatten()

array([2, 3, 4, 5])

The flatten() function is used to get a copy of an given array collapsed into one dimension.

In [ ]:
x = np.array([[1, 2, 3], [4, 5, 6]])
np.ravel(x)

numpy.ravel(a, order='C')
Return a contiguous flattened array.

In [3]:
np.all([[True,False],[True,True]], axis=0)

array([ True, False])

numpy.all(a, axis=None, out=None, keepdims=<no value>, *, where=<no value>)
Test whether all array elements along a given axis evaluate to True.

In [4]:
np.any([[True, False], [True, True]])

True

The numpy.any() function tests whether any array elements along the mentioned axis evaluate to True.

In [ ]:
b = np.array([[8,1,7], [4,3,9], [5,2,6]])
np.apply_along_axis(sorted, 1, b)

The numpy.apply_along_axis() function helps us to apply a required function to 1D slices of the given array.

In [5]:
my_1d_array = np.array([1,2,3,100,5])
np.argmax(a = my_1d_array)

3

 the argmax function returns the index of the maximum value of a Numpy array.

In [14]:
my_1d_array = np.array([10,2,3,100,5])
np.argmin(a = my_1d_array)

1

numpy.argmin(a, axis=None, out=None)
Returns the indices of the minimum values along an axis.

In [15]:
x = np.array([3, 1, 2])
np.argsort(x)

array([1, 2, 0])

numpy.argsort(a, axis=-1, kind=None, order=None)
Returns the indices that would sort an array.

In [16]:
data = np.arange(1, 5)
data

array([1, 2, 3, 4])

In [17]:
np.average(data)

2.5

numpy.average(a, axis=None, weights=None, returned=False)
Compute the weighted average along the specified axis.

In [18]:
np.bincount(np.array([0, 1, 1, 3, 2, 1, 7]))

array([1, 3, 1, 1, 0, 0, 0, 1])

numpy.bincount(x, weights=None, minlength=0)
Count number of occurrences of each value in array of non-negative ints

In [19]:
a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])
np.ceil(a)

array([-1., -1., -0.,  1.,  2.,  2.,  2.])

numpy.ceil(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj]) = <ufunc 'ceil'>
Return the ceiling of the input, element-wise.

In [20]:
a = np.arange(10)
np.clip(a, 1, 8)

array([1, 1, 2, 3, 4, 5, 6, 7, 8, 8])

numpy.clip(a, a_min, a_max, out=None, **kwargs)
Clip (limit) the values in an array

In [21]:
x = np.eye(2) + 1j * np.eye(2)
np.conjugate(x)

array([[1.-1.j, 0.-0.j],
       [0.-0.j, 1.-1.j]])

The numpy.conj() function helps the user to conjugate any complex number.

In [5]:
rng = np.random.default_rng(seed=42)
xarr = rng.random((3, 3))
xarr

array([[0.77395605, 0.43887844, 0.85859792],
       [0.69736803, 0.09417735, 0.97562235],
       [0.7611397 , 0.78606431, 0.12811363]])

In [6]:
R1 = np.corrcoef(xarr)
R1

array([[ 1.        ,  0.99256089, -0.68080986],
       [ 0.99256089,  1.        , -0.76492172],
       [-0.68080986, -0.76492172,  1.        ]])

numpy.corrcoef(x, y=None, rowvar=True, bias=<no value>, ddof=<no value>, *, dtype=None)
Return Pearson product-moment correlation coefficients.

In [7]:
x = np.array([[0, 2], [1, 1], [2, 0]]).T
x

array([[0, 1, 2],
       [2, 1, 0]])

In [8]:
np.cov(x)

array([[ 1., -1.],
       [-1.,  1.]])

Covariance provides the a measure of strength of correlation between two variable or more set of variables. The covariance matrix element Cij is the covariance of xi and xj. The element Cii is the variance of xi.

In [9]:
x = [1, 2, 3]
y = [4, 5, 6]
np.cross(x, y)

array([-3,  6, -3])

numpy.cross(a, b, axisa=-1, axisb=-1, axisc=-1, axis=None)
Return the cross product of two (arrays of) vectors.

In [10]:
a = np.array([[1, 2, 3], [4, 5, 6]])
np.cumprod(a, dtype=float)

array([  1.,   2.,   6.,  24., 120., 720.])

numpy.cumprod(a, axis=None, dtype=None, out=None)
Return the cumulative product of elements along a given axis.

In [11]:
np.cumsum(a)

array([ 1,  3,  6, 10, 15, 21])

numpy.cumsum(a, axis=None, dtype=None, out=None)
Return the cumulative sum of the elements along a given axis.

In [12]:
x = np.array([1, 2, 4, 7, 0])
np.diff(x)

array([ 1,  2,  3, -7])

Calculate the n-th discrete difference along the given axis.

In [13]:
np.dot(3, 4)

12

Dot product of two arrays

In [14]:
a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])
np.floor(a)

array([-2., -2., -1.,  0.,  1.,  1.,  2.])

The numpy.floor) is a mathematical function that returns the floor of the elements of array. The floor of the scalar x is the largest integer i, such that i <= x.

In [15]:
a = np.array([1,2,3])
b = np.array([0,1,0])
np.inner(a, b)

2

Numpy inner() method function returns the inner product of vectors for 1D arrays. For higher dimensions, it returns the sum-product over the last axes.

In [16]:
x = np.invert(np.array(13, dtype=np.uint8))
x

242

In [17]:
np.binary_repr(x, width=8)

'11110010'

numpy.invert() function is used to Compute the bit-wise Inversion of an array element-wise. It computes the bit-wise NOT of the underlying binary representation of the integers in the input arrays.

In [18]:
 a = np.array([[1, 2], [3, 4]])
np.mean(a)

2.5

In [19]:
np.maximum([2, 3, 4], [1, 5, 2])

array([2, 5, 4])

In [20]:
np.median(a)

2.5

In [21]:
np.minimum([2, 3, 4], [1, 5, 2])

array([1, 3, 2])

In [22]:
x = np.array([[3, 0, 0], [0, 4, 0], [5, 6, 0]])
x

array([[3, 0, 0],
       [0, 4, 0],
       [5, 6, 0]])

In [23]:
np.nonzero(x)

(array([0, 1, 2, 2]), array([0, 1, 0, 1]))

Return the indices of the elements that are non-zero.

In [24]:
rl = np.outer(np.ones((5,)), np.linspace(-2, 2, 5))
rl

array([[-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.]])

Compute the outer product of two vectors.

In [25]:
np.prod([1.,2.])

2.0

Return the product of array elements over a given axis.

In [26]:
np.round(1.5)

2.0

Round an array to the given number of decimals.

In [27]:
a = np.arange(8).reshape((2,2,2))
np.trace(a)

array([6, 8])

Return the sum along diagonals of the array.

In [28]:
x = np.arange(4).reshape((2,2))
x

array([[0, 1],
       [2, 3]])

In [29]:
np.transpose(x)

array([[0, 2],
       [1, 3]])

numpy.transpose(a, axes=None)
Reverse or permute the axes of an array; returns the modified array.

In [30]:
a = np.array([[1, 2], [3, 4]])
np.var(a)

1.25

Compute the variance along the specified axis.

In [31]:
a = np.array([1+2j,3+4j])
b = np.array([5+6j,7+8j])
np.vdot(a, b)

(70-8j)

Return the dot product of two vectors.

vectorize : The excluded argument can be used to prevent vectorizing over certain arguments. This can be useful for array-like arguments of a fixed length such as the coefficients for a polynomial as in polyval:

In [32]:
def mypolyval(p, x):
    _p = list(p)
    res = _p.pop(0)
    while _p:
        res = res*x + _p.pop(0)
    return res
vpolyval = np.vectorize(mypolyval, excluded=['p'])
vpolyval(p=[1, 2, 3], x=[0, 1])

array([3, 6])

In [33]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np.where(a < 5, a, 10*a)

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

In [35]:
x = np.array([1, 2, 2.5])
x

array([1. , 2. , 2.5])

In [36]:
x.astype(int)

array([1, 2, 2])

Copy of the array, cast to a specified type.

In [37]:
x = np.arange(9.0).reshape(3,3)
np.atleast_1d(x)

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

Convert inputs to arrays with at least one dimension.

In [38]:
x = np.arange(3.0)
np.atleast_2d(x)

array([[0., 1., 2.]])

View inputs as arrays with at least two dimensions.

In [39]:
np.atleast_3d(3.0)

array([[[3.]]])

View inputs as arrays with at least three dimensions.

In [40]:
x = np.arange(8.0)
np.array_split(x, 3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7.])]

Split an array into multiple sub-arrays.

In [41]:
a = np.arange(4).reshape(2,2)
a

array([[0, 1],
       [2, 3]])

In [42]:
a.diagonal()

array([0, 3])

Return specified diagonals.

In [43]:
x = np.arange(16.0).reshape(2, 2, 4)
x

array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.]],

       [[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]]])

In [44]:
np.dsplit(x, 2)

[array([[[ 0.,  1.],
         [ 4.,  5.]],
 
        [[ 8.,  9.],
         [12., 13.]]]), array([[[ 2.,  3.],
         [ 6.,  7.]],
 
        [[10., 11.],
         [14., 15.]]])]

Split array into multiple sub-arrays along the 3rd axis (depth).

In [45]:
a = np.array((1,2,3))
b = np.array((2,3,4))
np.dstack((a,b))

array([[[1, 2],
        [2, 3],
        [3, 4]]])

Stack arrays in sequence depth wise (along third axis).

In [46]:
x = np.random.randint(9, size=(3, 3))
x

array([[3, 6, 5],
       [1, 0, 4],
       [3, 2, 8]])

In [48]:
x.item((0, 1))

6

With the help of numpy.ndarray.item() method, we can fetch the data elements that is found at the given index on numpy array. Remember we can give index as one dimensional parameter or can be two dimensional.