**np.lexsort**

In [ ]:
Perform an indirect stable sort using a sequence of keys.

In [1]:
import numpy as np
surnames =    ('pathan','sayyed', 'pathan')    #Sort names: first by surname, then by name.
first_names = ('bushra','neha', 'sana')
a = np.lexsort((first_names, surnames))
a

array([0, 2, 1])

In [ ]:
[surnames[i] + ", " + first_names[i] for i in a ]

['pathan, bushra', 'pathan, sana', 'sayyed, neha']

Given multiple sorting keys, which can be interpreted as columns in a spreadsheet, lexsort returns an array of integer indices that describes the sort order by multiple columns. 


In [ ]:
a = [1,5,1,4,3,4,4]           # First column
b = [9,4,0,4,0,2,1]           # Second column
ind = np.lexsort((b,a)) 
ind                           # Sort by a, then by b


array([2, 0, 4, 6, 5, 3, 1])

In [ ]:
[(a[i],b[i]) for i in ind]

[(1, 0), (1, 9), (3, 0), (4, 1), (4, 2), (4, 4), (5, 4)]

sorting is first according to the elements of a. Secondary sorting is according to the elements of b.




**Structured arrays are sorted lexically by argsort.**

In [ ]:
[(a[i],b[i]) for i in np.argsort(a)]     #normal argsort

[(1, 9), (1, 0), (3, 0), (4, 4), (4, 2), (4, 1), (5, 4)]

In [ ]:
a = np.array([(1,9), (5,4), (1,0), (4,4), (3,0), (4,2), (4,1)],dtype=np.dtype([('x', int), ('y', int)]))
np.argsort(a)                               # or np.argsort(a, order=('x', 'y'))

array([2, 0, 4, 6, 5, 3, 1])

**np.searchsorted**

Find indices where elements should be inserted to maintain order.

Find the indices into a sorted array a such that, if the corresponding elements in v were inserted before the indices, the order of a would be preserved.

In [ ]:
np.searchsorted([1,2,3,4,5], 4)

3

In [ ]:
np.searchsorted([1,2,3,4,5], 2, side='right')

2

In [ ]:
np.searchsorted([1,2,3,4,5], [-10, 10, 2, 3])

array([0, 5, 1, 2])

**np.partition**

In [ ]:
a = np.array([3, 4, 2, 1])
np.partition(a, 3)


array([2, 1, 3, 4])

Creates a copy of the array with its elements rearranged in such a way that the value of the element in k-th position is in the position it would be in a sorted array.

In [ ]:
np.partition(a, (1, 3))

array([1, 2, 3, 4])

All elements smaller than the k-th element are moved before this element and all equal or greater are moved behind it. The ordering of the elements in the two partitions is undefined.

**np.concatenate**

Join a sequence of arrays along an existing axis.

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [ ]:
np.concatenate((a, b), axis=None)

array([1, 2, 3, 4, 5, 6])

**np.ndarray.ndim**

Number of array dimensions.

In [ ]:
x = np.array([1, 2, 3])
x.ndim

1

In [ ]:
y = np.zeros((2, 3, 4))
y.ndim

3

**np.ndarray.size**

Number of elements in the array.

Equal to np.prod(a.shape), i.e., the product of the array’s dimensions.

In [ ]:
x = np.zeros((3, 5, 2), dtype=np.complex128)
x.size

30

In [ ]:
np.prod(x.shape)    #np.prod(a.shape), which returns an instance of np.int

30

**np.ndarray.shape**

Tuple of array dimensions.

In [ ]:
x = np.array([1, 2, 3, 4])
x.shape

(4,)

In [ ]:
y = np.zeros((2, 3, 4))
y.shape

(2, 3, 4)

In [ ]:
y.shape = (3, 8)
y

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
a = np.random.randint(0,10,size=(3,2))   #random
a

array([[8, 3],
       [5, 0],
       [3, 4]])

Generate a 3 * 2 array of ints between 0 and 9, inclusive:

In [ ]:
a[a>5]

array([8])

In [ ]:
a>5

array([[ True, False],
       [False, False],
       [False, False]])

if the value is greater than 5 then it gives true instead value, other it gives false in above array.

In [ ]:
a[(a>5) & (a%2==0)]

array([8])

In [ ]:
a[(a<5) | (a%2==0)]

array([8, 3, 0, 3, 4])

In [ ]:
arr = np.arange(1,13)    #arrnge the element from 1 to 12 in 3*4 array
arr = arr.reshape(3,4)   #generate 3*4 array
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
b = np.nonzero(a<5)      #this gives row index and column index
b

(array([0, 1, 2, 2]), array([1, 1, 0, 1]))

In [ ]:
list(zip(b[0],b[1]))     #list of co-ordinates

[(0, 1), (1, 1), (2, 0), (2, 1)]

In [ ]:
a[b]                      #nonzero can be also used to directly fetch the elements

array([3, 0, 3, 4])

**slicing**

Slicing in python means taking elements from one given index to another given index.

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7]) 
(arr[1:5])                       #[start:end].

[2 3 4 5]


Slice elements from index 1 to index 5 from the above array

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
(arr[4:])

Slice elements from index 4 to the end of the array.

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
(arr[:4])

[1 2 3 4]


Slice elements from the beginning to index 4 (not included

**Negative Slicing**

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
(arr[-3:-1])

[5 6]


Slice from the index 3 from the end to index 1 from the end.

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])      #Return every other element from index 1 to index 5.
(arr[1:5:2])                          #[start:end:step].

[2 4]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])       #Return every other element from the entire array.
(arr[::2])

[1 3 5 7]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])       #Return every other element from the entire array.
(arr[::2])                               


array([1, 3, 5, 7])

**Slicing 2-D Arrays**

In [ ]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
(arr[1, 1:4])                                #From the second element, slice elements from index 1 to index 4 (not included)


array([7, 8, 9])

Note: Remember that second element has index 1.

In [ ]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
(arr[0:2, 2])                                #From both elements, return index 2:

array([3, 8])

**indexing**

Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [2]:
arr = np.array([1, 2, 3, 4])
(arr[0])                    #Get the first element from the following array.

1

In [3]:
arr = np.array([1, 2, 3, 4])
(arr[2] + arr[3])           #Get third and fourth elements from the following array and add them.

7

In [5]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])  
(arr[0, 1])                 #Access the 2nd element on 1st dim

2

In [10]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
(arr[1, 4])                 #Access the 5th element on 2nd dim

10

In [11]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
( arr[1, -1])                #Print the last element from the 2nd dim

10

**np.vstack()**

Stack arrays in sequence vertically (row wise).

In [12]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
np.vstack((a,b))

array([[1, 2, 3],
       [2, 3, 4]])

In [13]:
a = np.array([[1], [2], [3]])
b = np.array([[2], [3], [4]])
np.vstack((a,b))

array([[1],
       [2],
       [3],
       [2],
       [3],
       [4]])

**np.hstack()**

Stack arrays in sequence horizontally (column wise).

In [14]:
a = np.array((1,2,3))
b = np.array((2,3,4))
np.hstack((a,b))

array([1, 2, 3, 2, 3, 4])

In [15]:
a = np.array([[1],[2],[3]])
b = np.array([[2],[3],[4]])
np.hstack((a,b))

array([[1, 2],
       [2, 3],
       [3, 4]])

**np.hsplit()**

Split an array into multiple sub-arrays horizontally (column-wise).

In [16]:
x = np.arange(16.0).reshape(4, 4)
x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [17]:
np.hsplit(x, 2)

[array([[ 0.,  1.],
        [ 4.,  5.],
        [ 8.,  9.],
        [12., 13.]]), array([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.],
        [14., 15.]])]

In [18]:
np.hsplit(x, np.array([3, 6]))

[array([[ 0.,  1.,  2.],
        [ 4.,  5.,  6.],
        [ 8.,  9., 10.],
        [12., 13., 14.]]), array([[ 3.],
        [ 7.],
        [11.],
        [15.]]), array([], shape=(4, 0), dtype=float64)]

In [19]:
x = np.arange(8.0).reshape(2, 2, 2)
x

array([[[0., 1.],
        [2., 3.]],

       [[4., 5.],
        [6., 7.]]])

In [20]:
np.hsplit(x, 2)   #With a higher dimensional array the split is still along the second axis.

[array([[[0., 1.]],
 
        [[4., 5.]]]), array([[[2., 3.]],
 
        [[6., 7.]]])]

**.view()**

numpy.ndarray.view() helps to get a new view of array with the same data.

In [23]:
x = np.array([(1, 2)], dtype=[('a', np.int8), ('b', np.int8)])  

In [24]:
y = x.view(dtype=np.int16, type=np.matrix)   #Viewing array data using a different type and dtyp
y

matrix([[513]], dtype=int16)

In [25]:
x = np.array([(1, 2),(3,4)], dtype=[('a', np.int8), ('b', np.int8)])
xv = x.view(dtype=np.int8).reshape(-1,2)   #Creating a view on a structured array so it can be used in calculations
xv

array([[1, 2],
       [3, 4]], dtype=int8)

In [26]:
xv.mean(0)

array([2., 3.])

In [27]:
xv[0,1] = 20     #Making changes to the view changes the underlying array
x

array([(1, 20), (3,  4)], dtype=[('a', 'i1'), ('b', 'i1')])

In [28]:
z = x.view(np.recarray)       #Using a view to convert an array to a recarray.
z.a

array([1, 3], dtype=int8)

In [29]:
x[0] = (9, 10)  #view share data.
z[0]

(9, 10)

**copy()**

Return an array copy of the given object.

In [32]:
x = np.array([1, 2, 3])
y = x          #Create an array x, with a reference y and a copy z.

In [36]:
x[0] = 10
x[0] == y[0]         # when we modify x, y changes, but not z


True

In [35]:
x[0] == z[0]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: elementwise == comparison failed and returning scalar instead; this will raise an error or perform elementwise comparison in the future.
  """Entry point for launching an IPython kernel.


False

In [37]:
a = np.array([1, 'm', [2, 3, 4]], dtype=object)
b = np.copy(a)
b[2][0] = 10
a

array([1, 'm', list([10, 3, 4])], dtype=object)

np.copy is a shallow copy and will not copy object elements within arrays.

 The new array will contain the same object which may lead to surprises if that object can be modified (is mutable):

In [38]:
 import copy
a = np.array([1, 'm', [2, 3, 4]], dtype=object)
c = copy.deepcopy(a)
c[2][0] = 10                                                  

In [39]:
a

array([1, 'm', list([2, 3, 4])], dtype=object)

 ensure all elements within an object array are copied, use copy.deepcopy:

In [40]:
arr = np.array([[1, 1], [2, 2]])
arr

array([[1, 1],
       [2, 2]])

In [41]:
arr.sum()

6

In [42]:
arr.sum(axis=0)

array([3, 3])

This function returns the sum of array elements over the specified axis.

In [43]:
arr.sum(axis=1)  #it gives the sum of the rows.

array([2, 4])

**np.unique**

Find the unique elements of an array.

Returns the sorted unique elements of an array. There are three optional outputs in addition to the unique elements.

In [44]:
np.unique([1, 1, 2, 2, 3, 3])

array([1, 2, 3])

In [45]:
a = np.array([[1, 1], [2, 3]])
np.unique(a)

array([1, 2, 3])

In [46]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])
np.unique(a_2d, axis=0)      #Return the unique rows of a 2D array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [47]:
a_2d = np.array([[1, 2, 3, 1], [5, 6, 7, 5], [9, 10, 11, 9], [1, 2, 3, 1]])
a_2d = np.unique(a_2d, axis=0)    # Removes duplicate rows
a_2d

array([[ 1,  2,  3,  1],
       [ 5,  6,  7,  5],
       [ 9, 10, 11,  9]])

In [48]:
a_2d = np.unique(a_2d, axis=1) # Removes duplicate columns
a_2d

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [49]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])
unique_rows, indices, occurrence_count = np.unique(
                                            a_2d, axis=0, return_counts=True, return_index=True)
(unique_rows)

(indices)                 # returns indices of unique rows
(occurrence_count)         # returns count of rows

array([2, 1, 1])

**np.flip**

Reverse the order of elements in an array along the given axis.

The shape of the array is preserved, but the elements are reordered.

In [50]:
A = np.arange(8).reshape((2,2,2))
A

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [51]:
np.flip(A, 0)

array([[[4, 5],
        [6, 7]],

       [[0, 1],
        [2, 3]]])

In [52]:
np.flip(A, 1)

array([[[2, 3],
        [0, 1]],

       [[6, 7],
        [4, 5]]])

In [53]:
np.flip(A)

array([[[7, 6],
        [5, 4]],

       [[3, 2],
        [1, 0]]])

In [54]:
np.flip(A, (0, 2))

array([[[5, 4],
        [7, 6]],

       [[1, 0],
        [3, 2]]])

In [55]:
A = np.random.randn(3,4,5)
np.all(np.flip(A,2) == A[:,:,::-1,...])

True

**flatten()**

Return a copy of the array collapsed into one dimension.


In [56]:
a = np.array([[1,2], [3,4]])
a.flatten()

array([1, 2, 3, 4])

In [57]:
a.flatten('F')  # copied columnwise

array([1, 3, 2, 4])

**ravel()**

Return a contiguous flattened array.

In [61]:
x = np.array([[1, 2, 3], [4, 5, 6]])  #It is equivalent to reshape(-1, order=order).
np.ravel(x)

array([1, 2, 3, 4, 5, 6])

In [62]:
x.reshape(-1)


array([1, 2, 3, 4, 5, 6])

In [63]:
np.ravel(x, order='F')

array([1, 4, 2, 5, 3, 6])

In [64]:
np.ravel(x.T)

array([1, 4, 2, 5, 3, 6])

In [ ]:
np.ravel(x.T, order='A')

When order is ‘A’, it will preserve the array’s ‘C’ or ‘F’ ordering.