In [2]:
%config Completer.use_jedi = False

In [3]:
import numpy as np

In [4]:
# similar to range in python
# numpy.arange([start, ]stop, [step, ], dtype=None) 
a = np.arange(0,12,2)
print(a)

[ 0  2  4  6  8 10]


In [5]:
# gives a tuple of number of elements in each axis
a.shape

(6,)

### Adding a new axis

In [6]:
temp = a[np.newaxis,:]
temp.shape

(1, 6)

In [6]:
a.reshape(1,-1).shape

(1, 6)

In [7]:
a[:,np.newaxis].shape

(6, 1)

In [8]:
a.reshape(-1,1).shape

(6, 1)

In [51]:
np.expand_dims(a,axis=1).shape

(6, 1)

In [52]:
np.expand_dims(a,axis=0).shape

(1, 6)

In [7]:
a[None,:].shape

(1, 6)

In [8]:
a[:,None].shape

(6, 1)

### numpy functions to create arrays

In [9]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [10]:
np.ones(shape=(4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [11]:
np.empty(shape=(2,3,4)) #This isfaster than np.zeros

array([[[ 2.41440681e-310,  2.34140334e-258,  2.21649092e-313,
          6.18196790e-309],
        [-2.08005242e-046,  5.20374872e-259,  1.53229019e-231,
          1.53543648e-231],
        [ 1.73315714e-260,  2.18354929e-289,  2.18254133e-289,
          5.38726887e-299]],

       [[ 9.41267931e-280,  3.19271975e-241,  7.43703987e-251,
          4.67044207e-193],
        [ 2.97742215e-212,  5.88411975e-222,  7.44044338e-251,
          7.44044312e-251],
        [ 4.67258231e-193,  1.37251949e-231,  4.67472275e-193,
          4.67686319e-193]]])

### Creating arrays

In [18]:
np.linspace(1,100,20)

array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ])

In [22]:
np.random.rand(3,2,1) # random array with shape (3,2,1)

array([[[0.42597685],
        [0.37818109]],

       [[0.90820233],
        [0.63159878]],

       [[0.04142703],
        [0.3885689 ]]])

In [9]:
np.random.randint(low=0,high=5,size=(3,2)) 

array([[3, 0],
       [3, 1],
       [3, 4]])

In [35]:
np.random.randn(3,2,2) #random normal distribution

array([[[ 0.07158827,  0.00594014],
        [-0.4593867 ,  0.52635941]],

       [[ 0.32097379,  1.02098771],
        [ 0.85041277, -0.33071488]],

       [[-0.06820504,  1.0533379 ],
        [-1.36162735,  0.1811919 ]]])

### Sorting

In [17]:
arr = np.random.randint(0,5,size=(6,))
arr

array([3, 0, 0, 1, 2, 4])

In [18]:
np.sort(arr) # not inplace sorting

array([0, 0, 1, 2, 3, 4])

In [16]:
arr

array([4, 0, 1, 4, 0])

In [47]:
arr.sort() # inplace sorting

In [13]:
arr

array([1, 2, 2, 4, 4])

In [21]:
temp = arr.reshape(3,2)
temp

array([[3, 0],
       [0, 1],
       [2, 4]])

In [37]:
np.sort(temp,axis=1)

array([[0, 3],
       [0, 1],
       [2, 4]])

In [38]:
# Indirect sorting using argsort
ind = np.argsort(temp,axis=1) # Returns the indices that would sort the array
ind

array([[1, 0],
       [0, 1],
       [0, 1]], dtype=int64)

In [42]:
np.take_along_axis(temp,ind,axis=0)

array([[0, 0],
       [3, 1],
       [3, 1]])

In [43]:
# sorting with keys

In [ ]:
# lexsort, which is an indirect stable sort on multiple keys,

In [49]:
#     searchsorted, which will find elements in a sorted array, and

#     partition, which is a partial sort.

### stacking arrays

In [44]:
a = np.array([[1, 2], [3, 4]]) 
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [88]:
# similar to vstack
a = np.array([[1, 2], [3, 4]]) 
b = np.array([[5, 6]])
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [89]:
# Similar to row_stack
np.row_stack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [91]:
# Similar to np.r_
np.r_[a,b]

array([[1, 2],
       [3, 4],
       [5, 6]])

In [92]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6],[1,2]])
np.concatenate((a, b), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 1, 2]])

In [93]:
# Similar to hstack
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6],[1,2]])
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 1, 2]])

In [94]:
# Similar to column_stack
np.column_stack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 1, 2]])

In [95]:
# Similar to np.c_
np.c_[a,b]

array([[1, 2, 5, 6],
       [3, 4, 1, 2]])

In [47]:
np.concatenate((a, b), axis=None)

array([1, 2, 3, 4, 5, 6, 1, 2])

In [53]:
# np.ndarray.ndim
# np.ndarray.size
# np.ndarray.shape

In [13]:
a = np.random.randint(0,10,size=(3,2))
a

array([[7, 0],
       [7, 4],
       [7, 7]])

In [14]:
a>5

array([[ True, False],
       [ True, False],
       [ True,  True]])

In [57]:
a[a>5]

array([9, 8, 9])

In [60]:
a>5

array([[ True, False],
       [False, False],
       [ True,  True]])

In [58]:
a[(a>5) & (a%2==0)]

array([8])

In [59]:
a[(a<5) | (a%2==0)]

array([1, 2, 3, 8])

In [66]:
arr = np.arange(1,13)
arr = arr.reshape(3,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [68]:
b = np.nonzero(a<5) #this gives row index and column index
b

(array([0, 1, 1], dtype=int64), array([1, 0, 1], dtype=int64))

In [71]:
list(zip(b[0],b[1])) #list of co-ordinates

[(0, 1), (1, 0), (1, 1)]

In [72]:
a[b] #nonzero can be also used to directly fetch the elements

array([1, 2, 3])

### slicing 

In [49]:
arr = np.arange(12).reshape(4,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [50]:
arr[1:3,1:]

array([[4, 5],
       [7, 8]])

In [54]:
arr[1,1:3]

array([4, 5])

In [55]:
arr[1:3,1]

array([4, 7])

In [73]:
# indexing
# np.hsplit()
# .view()
# copy() vs deepcopy()

### unique

In [ ]:
# np.unique
# unique_values, indices_list = np.unique(a, return_index=True)
# unique_values, occurrence_count = np.unique(a, return_counts=True)

In [59]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])
np.unique(a_2d, axis=0) # Removes duplicate rows
    

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [60]:
a_2d = np.array([[1, 2, 3, 1], [5, 6, 7, 5], [9, 10, 11, 9], [1, 2, 3, 1]])
a_2d = np.unique(a_2d, axis=0) # Removes duplicate rows
a_2d

array([[ 1,  2,  3,  1],
       [ 5,  6,  7,  5],
       [ 9, 10, 11,  9]])

In [61]:
a_2d = np.unique(a_2d, axis=1) # Removes duplicate columns
a_2d

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [88]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])
unique_rows, indices, occurrence_count = np.unique(
                                            a_2d, axis=0, return_counts=True, return_index=True)
print(unique_rows)

print(indices) # returns indices of unique rows
print(occurrence_count) # returns count of rows

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[0 1 2]
[2 1 1]


### np.flip / reverse an array

### Flatten an array

In [ ]:
# flatten() # data is copied
# ravel() # This is view of the original

In [62]:
a = np.array([[1,2], [3,4]])
a.flatten()

array([1, 2, 3, 4])

In [63]:
a.flatten('F')  # copied columnwise

array([1, 3, 2, 4])

In [65]:
a = np.array([[1,2], [3,4]])
np.ravel(a)

array([1, 2, 3, 4])

In [67]:
a = np.array([[1,2], [3,4]])
np.ravel(a,order='F')

array([1, 3, 2, 4])

### Important Functions

In [ ]:
# all, any, apply_along_axis, argmax, argmin, argsort, average, bincount, ceil, clip, conj, 
# corrcoef, cov, cross, cumprod, cumsum, diff, dot, floor, inner, invert, lexsort, max, 
# maximum, mean, median, min, minimum, nonzero, outer, prod, re, round, sort, std, sum, trace, 
# transpose, var, vdot, vectorize, where

In [68]:
c = [[True, False], [True, True]]
arr = np.all(c)
arr

False

In [70]:
c = [[1, 1], [1, 1]]
arr = np.all(c)
arr

True

In [71]:
c = [[True, False], [True, True]]
arr = np.any(c)
arr

True

In [73]:
c = [[0, 0], [0, 0]]
arr = np.any(c)
arr

False

In [76]:
def func(a):
    return (a[0]+ a[-1])   
arr = np.array([[2,4,6],    
              [1,3,5],     
              [9,7,8]])    
np.apply_along_axis(func,axis=0,arr=arr) # Sum first and last element column wise

array([11, 11, 14])

In [77]:
def func(a):
    return (a[0]+ a[-1])   
arr = np.array([[2,4,6],    
              [1,3,5],     
              [9,7,8]])    
np.apply_along_axis(func,axis=1,arr=arr) # Sum first and last element row wise

array([ 8,  6, 17])

In [94]:
def func(row,col):
    return (row+col)

np.fromfunction(func,(5,4),dtype=int)

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

In [ ]:
# argmax/argmin -Return indices of the maximum values along the given axis.


In [83]:
'''
This will create an array of size max(arr)+1
It will give the count of elemnets at respective index
This will only work for +ve values
'''
np.bincount([4,6,7,4,2,4])

array([0, 0, 1, 0, 3, 0, 1, 1], dtype=int64)

In [85]:
'''
Any element <= a_min will be clipped
Any element >= a_max will be clipped
'''
arr = np.arange(10)
np.clip(arr,a_min=2,a_max=7)

array([2, 2, 2, 3, 4, 5, 6, 7, 7, 7])

In [95]:
# The dots (...) represent as many colons as needed to produce a complete indexing tuple. 
# For example, if x is an array with 5 axes, then

#     x[1,2,...] is equivalent to x[1,2,:,:,:],

#     x[...,3] to x[:,:,:,:,3] and

#     x[4,...,5,:] to x[4,:,:,5,:].


In [96]:
# Indexing, Indexing (reference), newaxis, ndenumerate, indices


### reshape / resize

In [99]:
a = np.random.rand(2,3)
a.reshape(3,2) #not inplace

array([[0.55874008, 0.67293368],
       [0.9141838 , 0.62341736],
       [0.21266514, 0.5824323 ]])

In [102]:
a = np.random.rand(2,3)
a.resize(3,2) # inplace operation
a

array([[0.46739584, 0.88212774],
       [0.58113407, 0.53649547],
       [0.50867788, 0.32805752]])

In [ ]:
# Array Creation

#     arange, array, copy, empty, empty_like, eye, fromfile, fromfunction, identity, 
# linspace, logspace, mgrid, ogrid, ones, ones_like, r_, zeros, zeros_like
# Conversions

#     ndarray.astype, atleast_1d, atleast_2d, atleast_3d, mat
# Manipulations

#     array_split, column_stack, concatenate, diagonal, dsplit, dstack, hsplit, hstack, ndarray.item, 
# newaxis, ravel, repeat, reshape, resize, squeeze, swapaxes, take, transpose, vsplit, vstack

# Questions

#     all, any, nonzero, where
# Ordering

#     argmax, argmin, argsort, max, min, ptp, searchsorted, sort
# Operations

#     choose, compress, cumprod, cumsum, inner, ndarray.fill, imag, prod, put, putmask, real, sum
    
# Basic Statistics

#     cov, mean, std, var
# Basic Linear Algebra

#     cross, dot, outer, linalg.svd, vdot


In [ ]:
# np.ix_()

In [104]:
# numpy ufunc

In [74]:
arr = np.array([[1, 1], [2, 2]])
arr

arr.sum()

arr.sum(axis=0)

arr.sum(axis=1)

array([[1, 1],
       [2, 2]])