In [1]:
%config Completer.use_jedi = False

In [2]:
import numpy as np

In [3]:
a = np.arange(0,12,2) # similar to range
print(a)

[ 0  2  4  6  8 10]


In [4]:
a.shape

(6,)

### Adding a new axis

In [5]:
a[np.newaxis,:].shape

(1, 6)

In [6]:
a.reshape(1,-1).shape

(1, 6)

In [7]:
a[:,np.newaxis].shape

(6, 1)

In [8]:
a.reshape(-1,1).shape

(6, 1)

In [51]:
np.expand_dims(a,axis=1).shape

(6, 1)

In [52]:
np.expand_dims(a,axis=0).shape

(1, 6)

### numpy functions to create arrays

In [9]:
np.zeros(2)

array([0., 0.])

In [10]:
np.ones(shape=(4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [11]:
np.empty(shape=(2,3,4)) #This isfaster than np.zeros

array([[[ 2.41440681e-310,  2.34140334e-258,  2.21649092e-313,
          6.18196790e-309],
        [-2.08005242e-046,  5.20374872e-259,  1.53229019e-231,
          1.53543648e-231],
        [ 1.73315714e-260,  2.18354929e-289,  2.18254133e-289,
          5.38726887e-299]],

       [[ 9.41267931e-280,  3.19271975e-241,  7.43703987e-251,
          4.67044207e-193],
        [ 2.97742215e-212,  5.88411975e-222,  7.44044338e-251,
          7.44044312e-251],
        [ 4.67258231e-193,  1.37251949e-231,  4.67472275e-193,
          4.67686319e-193]]])

### Creating arrays

In [18]:
np.linspace(1,100,20)

array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ])

In [22]:
np.random.rand(3,2,1) # random array with shape (3,2,1)

array([[[0.42597685],
        [0.37818109]],

       [[0.90820233],
        [0.63159878]],

       [[0.04142703],
        [0.3885689 ]]])

In [32]:
np.random.randint(0,5,size=(3,2))

array([[3, 3],
       [0, 1],
       [0, 4]])

In [35]:
np.random.randn(3,2,2) #random normal distribution

array([[[ 0.07158827,  0.00594014],
        [-0.4593867 ,  0.52635941]],

       [[ 0.32097379,  1.02098771],
        [ 0.85041277, -0.33071488]],

       [[-0.06820504,  1.0533379 ],
        [-1.36162735,  0.1811919 ]]])

In [45]:
arr = np.random.randint(0,5,size=(5,))
arr

array([4, 4, 2, 3, 1])

In [44]:
np.sort(arr) # not inplace sorting

array([1, 2, 3, 3, 4])

In [46]:
arr

array([4, 4, 2, 3, 1])

In [47]:
arr.sort() # inplace sorting

In [48]:
arr

array([1, 2, 3, 4, 4])

In [49]:
# #

#     argsort, which is an indirect sort along a specified axis,

#     lexsort, which is an indirect stable sort on multiple keys,

#     searchsorted, which will find elements in a sorted array, and

#     partition, which is a partial sort.


In [50]:
# np.concatenate

In [53]:
# np.ndarray.ndim
# np.ndarray.size
# np.ndarray.shape

In [56]:
a = np.random.randint(0,10,size=(3,2))
a

array([[9, 1],
       [2, 3],
       [8, 9]])

In [57]:
a[a>5]

array([9, 8, 9])

In [60]:
a>5

array([[ True, False],
       [False, False],
       [ True,  True]])

In [58]:
a[(a>5) & (a%2==0)]

array([8])

In [59]:
a[(a<5) | (a%2==0)]

array([1, 2, 3, 8])

In [66]:
arr = np.arange(1,13)
arr = arr.reshape(3,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [68]:
b = np.nonzero(a<5) #this gives row index and column index
b

(array([0, 1, 1], dtype=int64), array([1, 0, 1], dtype=int64))

In [71]:
list(zip(b[0],b[1])) #list of co-ordinates

[(0, 1), (1, 0), (1, 1)]

In [72]:
a[b] #nonzero can be also used to directly fetch the elements

array([1, 2, 3])

In [73]:
# slicing 
# indexing
# np.vstack()
# np.hstack()
# np.hsplit()
# .view()
# copy()

In [74]:
arr = np.array([[1, 1], [2, 2]])
arr

array([[1, 1],
       [2, 2]])

In [75]:
arr.sum()

6

In [76]:
arr.sum(axis=0)

array([3, 3])

In [77]:
arr.sum(axis=1)

array([2, 4])

In [78]:
# np.unique
# unique_values, indices_list = np.unique(a, return_index=True)
# unique_values, occurrence_count = np.unique(a, return_counts=True)


In [81]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])
np.unique(a_2d, axis=0)
    

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [84]:
a_2d = np.array([[1, 2, 3, 1], [5, 6, 7, 5], [9, 10, 11, 9], [1, 2, 3, 1]])
a_2d = np.unique(a_2d, axis=0) # Removes duplicate rows
a_2d

array([[ 1,  2,  3,  1],
       [ 5,  6,  7,  5],
       [ 9, 10, 11,  9]])

In [85]:
a_2d = np.unique(a_2d, axis=1) # Removes duplicate columns
a_2d

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [88]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])
unique_rows, indices, occurrence_count = np.unique(
                                            a_2d, axis=0, return_counts=True, return_index=True)
print(unique_rows)

print(indices) # returns indices of unique rows
print(occurrence_count) # returns count of rows

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[0 1 2]
[2 1 1]


In [89]:
# np.flip #reverse an array

In [91]:
# flatten() # data is copied
# ravel() # This is view of the original

In [ ]:
# all, any, apply_along_axis, argmax, argmin, argsort, average, bincount, ceil, clip, conj, 
# corrcoef, cov, cross, cumprod, cumsum, diff, dot, floor, inner, invert, lexsort, max, 
# maximum, mean, median, min, minimum, nonzero, outer, prod, re, round, sort, std, sum, trace, 
# transpose, var, vdot, vectorize, where

In [94]:
def func(row,col):
    return (row+col)

np.fromfunction(func,(5,4),dtype=int)

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

In [95]:
# The dots (...) represent as many colons as needed to produce a complete indexing tuple. For example, if x is an array with 5 axes, then

#     x[1,2,...] is equivalent to x[1,2,:,:,:],

#     x[...,3] to x[:,:,:,:,3] and

#     x[4,...,5,:] to x[4,:,:,5,:].


In [96]:
# Indexing, Indexing (reference), newaxis, ndenumerate, indices


In [99]:
a = np.random.rand(2,3)
a.reshape(3,2) #not inplace

array([[0.55874008, 0.67293368],
       [0.9141838 , 0.62341736],
       [0.21266514, 0.5824323 ]])

In [102]:
a = np.random.rand(2,3)
a.resize(3,2) # inplace operation
a

array([[0.46739584, 0.88212774],
       [0.58113407, 0.53649547],
       [0.50867788, 0.32805752]])

In [103]:
# column_stack, row_stack, concatenate, c_, r_


In [ ]:
# Array Creation

#     arange, array, copy, empty, empty_like, eye, fromfile, fromfunction, identity, linspace, logspace, mgrid, ogrid, ones, ones_like, r_, zeros, zeros_like
# Conversions

#     ndarray.astype, atleast_1d, atleast_2d, atleast_3d, mat
# Manipulations

#     array_split, column_stack, concatenate, diagonal, dsplit, dstack, hsplit, hstack, ndarray.item, newaxis, ravel, repeat, reshape, resize, squeeze, swapaxes, take, transpose, vsplit, vstack
# Questions

#     all, any, nonzero, where
# Ordering

#     argmax, argmin, argsort, max, min, ptp, searchsorted, sort
# Operations

#     choose, compress, cumprod, cumsum, inner, ndarray.fill, imag, prod, put, putmask, real, sum
    
# Basic Statistics

#     cov, mean, std, var
# Basic Linear Algebra

#     cross, dot, outer, linalg.svd, vdot


In [ ]:
# np.ix_()

In [104]:
# numpy ufunc